AWSTemplateFormatVersion: '2010-09-09'

Mappings:
  CidrBlocks:
    Dev:
      Public1: 20.0.1.0/24
      Public2: 20.0.2.0/24
      Private1: 20.0.10.0/24
      Private2: 20.0.11.0/24
    Prod:
      Public1: 20.0.3.0/24
      Public2: 20.0.4.0/24
      Private1: 20.0.20.0/24
      Private2: 20.0.21.0/24

Parameters:
  Ambiente:
    Type: String
    Default: Dev
    AllowedValues: [Dev, Prod]
  VpcDestinoPeering:
    Type: AWS::EC2::VPC::Id
  PublicSubnet1Cidr:
    Type: String
    Default: 20.0.1.0/24
    Description: CIDR para subred publica 1
  PublicSubnet2Cidr:
    Type: String
    Default: 20.0.2.0/24
    Description: CIDR para subred publica 2
  PrivateSubnet1Cidr:
    Type: String
    Default: 20.0.10.0/24
    Description: CIDR para subred privada 1
  PrivateSubnet2Cidr:
    Type: String
    Default: 20.0.11.0/24
    Description: CIDR para subred privada 2



Resources:
  MiVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 20.0.0.0/16

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MiVPC
      CidrBlock: !Ref PublicSubnet1Cidr
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MiVPC
      CidrBlock: !Ref PublicSubnet2Cidr
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MiVPC
      CidrBlock: !Ref PrivateSubnet1Cidr
      AvailabilityZone: !Select [0, !GetAZs '']

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MiVPC
      CidrBlock: !Ref PrivateSubnet2Cidr
      AvailabilityZone: !Select [1, !GetAZs '']

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MiVPC
      InternetGatewayId: !Ref InternetGateway

  EIPNatGateway:
    Type: AWS::EC2::EIP
    DependsOn: AttachGateway
    Properties:
      Domain: vpc

  NatGateway:
    Type: AWS::EC2::NatGateway
    DependsOn: AttachGateway
    Properties:
      AllocationId: !GetAtt EIPNatGateway.AllocationId
      SubnetId: !Ref PublicSubnet1

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MiVPC

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicRTAssoc1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicRTAssoc2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MiVPC

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway

  PrivateRTAssoc1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable

  PrivateRTAssoc2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable

  VpcPeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !Ref MiVPC
      PeerVpcId: !Ref VpcDestinoPeering

  PeeringRoutePublic:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 172.31.0.0/16
      VpcPeeringConnectionId: !Ref VpcPeeringConnection

  PeeringRoutePrivate:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 172.31.0.0/16
      VpcPeeringConnectionId: !Ref VpcPeeringConnection

Outputs:
  VPCId:
    Description: ID de la VPC creada
    Value: !Ref MiVPC
  
  PublicSubnet1Id:
    Description: ID de la subred publica 1
    Value: !Ref PublicSubnet1
  
  PublicSubnet2Id:
    Description: ID de la subred publica 2
    Value: !Ref PublicSubnet2
  
  PrivateSubnet1Id:
    Description: ID de la subred privada 1
    Value: !Ref PrivateSubnet1
  
  PrivateSubnet2Id:
    Description: ID de la subred privada 2
    Value: !Ref PrivateSubnet2
  
  NatGatewayId:
    Description: ID del NAT Gateway
    Value: !Ref NatGateway
