AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  CrearInstancia:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'true'
    Description: Indica si se crea la instancia EC2 (true/false).

  InstanceType:
    Type: String
    Default: t3.micro
    Description: Tipo de instancia EC2.
    AllowedValues:
      - t3.micro
      - t3.small
      - t3.medium

Conditions:
  CrearInstanciaCond: !Equals [!Ref CrearInstancia, 'true']



Resources:
  MiVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: MiVPC

  SubredPublica:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MiVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: SubredPublica

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MiVPC
      InternetGatewayId: !Ref InternetGateway

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MiVPC
      Tags:
        - Key: Name
          Value: RouteTablePublica

  RoutePublica:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  AsociarSubredPublica:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubredPublica
      RouteTableId: !Ref RouteTable

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2 instance
      VpcId: !Ref MiVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: SecurityGroup-EC2

  InstanciaEC2:
    Type: AWS::EC2::Instance
    Condition: CrearInstanciaCond
    Properties:
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}'
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SubredPublica
      SecurityGroupIds:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: !Join ['', [!Ref 'AWS::Region', '-Karim']]
        - Key: VPCID
          Value: !GetAtt MiVPC.VpcId
